services:

###### Caddy Proxy Docker

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    environment:
      - CADDY_INGRESS_NETWORKS=caddymanager
    networks:
      - caddymanager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

###### Exemplo Labels

  page:
    image: tonanuvem/fiap_page
    networks:
      - caddymanager
    labels:
      caddy: page.vm.aluno.lab.tonanuvem.com
      caddy.reverse_proxy: "{{upstreams 80}}"

###### Caddy Manager

    caddy-ui:
      image: qmcgaw/caddy-ui
      ports:
        - 8880:8000/tcp
      environment:
        - CADDY_API_ENDPOINT=http://caddy:2019
    networks:
      - caddymanager
    restart: unless-stopped
      
###### Caddy Manager

  # MongoDB database for persistent storage
  mongodb:
    image: mongo:8.0
    container_name: caddymanager-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=someSecretPassword  # Change for production!
    ports:
      - "27017:27017"  # Expose for local dev, remove for production
    volumes:
      - mongodb_data:/data/db
    networks:
      - caddymanager

  # Backend API server
  backend:
    image: caddymanager/caddymanager-backend:latest
    container_name: caddymanager-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongoadmin:someSecretPassword@mongodb:27017/caddymanager?authSource=admin
      #- CORS_ORIGIN=http://caddy:5173
      - CORS_ORIGIN=*
      - LOG_LEVEL=debug
      - DEFAULT_CADDY_ADMIN_USER=fiap
      - DEFAULT_CADDY_ADMIN_PASSWORD=fiap
      - CADDY_SANDBOX_URL=http://caddy:2019
      - PING_INTERVAL=30000
      - PING_TIMEOUT=2000
      - AUDIT_LOG_MAX_SIZE_MB=100
      - AUDIT_LOG_RETENTION_DAYS=90
      - JWT_SECRET=your_jwt_secret_key_here  # Change for production!
      - JWT_EXPIRATION=24h
    ports:
      - "3000:3000"  # Expose API
    networks:
      - caddymanager

  # Frontend web UI
  frontend:
    image: caddymanager/caddymanager-frontend:latest
    container_name: caddymanager-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:3000/api/v1
      - APP_NAME=Caddy Manager
      - DARK_MODE=true
    ports:
      - "8888:80"  # Expose web UI
    networks:
      - caddymanager

networks:
  caddymanager:
    driver: bridge

volumes:
  mongodb_data:
  caddy_data: {}
